server:
  port: 8079

spring:
  application:
    name: API-GATEWAY
  cloud:
    discovery:
      reactive:
        enabled: false
    gateway:
      locator:
        enabled: true
      routes:
        - id: service1-route
          uri: lb://SERVICE1/
          predicates:
            - Path=/products/**
        - id: service2-route
          uri: lb://SERVICE2/
          predicates:
            - Path=/service2/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL} #http://192.168.0.100:8761/eureka/  # Eureka Server

  instance:
    hostname: api-gateway
    prefer-ip-address: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
