spring:
  application:
    name: coupon-service

#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE}

  cloud:
    stream:
      bindings:
        payment-out-0:
          destination: payment-events
    config:
      import-check:
        enabled: false
#    discovery:
#      enabled: true
#    config:
#      uri: ${CONFIG_SERVER_URL}

  config:
    import-check:
      enabled: false
#    import: configserver:${CONFIG_SERVER_URL}

  datasource:
    url: jdbc:postgresql://localhost:5432/coupon_db
    username: maciejwnuklipinski
    password: pswd
    driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: validate

#  datasource:
#    url: jdbc:h2:mem:coupondb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

resilience4j:
  retry:
    instances:
      geoip:
        max-attempts: 3
        wait-duration: 1000ms # Wait half a second before retrying
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true