server:
  port: 8081

spring:
  application:
    name: usage-service

#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE}

  cloud:
    stream:
      bindings:
        payment-out-0:
          destination: payment-events
    config:
      import-check:
        enabled: false
    discovery:
      enabled: false
#    discovery:
#      enabled: true
#    config:
#      uri: ${CONFIG_SERVER_URL}

  config:
    import-check:
      enabled: false
#    import: configserver:${CONFIG_SERVER_URL}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/usage_db
    username: maciejwnuklipinski
    password: pswd
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

app:
  coupon-service:
    url: http://localhost:${wiremock.server.port}
  geoip:
    proxy:
      enabled: true
      host: 154.73.28.89
      port: 8080
    ip-api:
      url: https://ipapi.co/
    abstract-api:
      url: https://ip-intelligence.abstractapi.com
      key: 82fcff2895fd408b8aff6c1dd78e3292 #${ABSTRACT_API_KEY:your_default_key}

coupon-service:
  url: http://localhost:${wiremock.server.port}

resilience4j:
  retry:
    retry-aspect-order: 399
    circuitbreaker:
      circuit-breaker-aspect-order: 400
    instances:
      couponServiceRetry:
        maxAttempts: 3
        waitDuration: 200ms
        retryExceptions:
          - com.redemption.usage.domain.exception.UsageException$ConcurrencyConflict
          - com.redemption.usage.domain.exception.UsageException$RemoteServiceError
      geoip:
        maxAttempts: 2
        waitDuration: 500ms
  circuitbreaker:
    instances:
      geoipCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
      internalServiceCB:
        registerHealthIndicator: true      # Exposes circuit breaker status via Actuator /health endpoint
        slidingWindowSize: 10              # Number of calls to record and analyze for the threshold
        failureRateThreshold: 50           # Opens the circuit if 50% or more calls fail
        waitDurationInOpenState: 10000ms   # Time to wait before transitioning from OPEN to HALF_OPEN
        permittedNumberOfCallsInHalfOpenState: 3 # Number of test calls allowed to verify service recovery
        slowCallRateThreshold: 100         # Percentage of slow calls required to open the circuit
        slowCallDurationThreshold: 2000ms  # Maximum duration allowed before a call is considered "slow"

# Feign
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
  show-actuator: true